apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
type: Opaque
stringData:
  EMAIL_USER: "nexusai.workspacke@gmail.com"
  APP_PASSWORD: "kkhy ritm ohhc tmis"
  NEXTAUTH_SECRET: "BANKAI"
  JWT_SECRET: "BANKAI" 