apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  FRONTEND_URL: "http://frontend.dev.svc.cluster.local:3000"
  DB_HOST: "postgres.dev.svc.cluster.local"
  DB_PORT: "5432"
  DATABASE_URL: "postgres://postgres:postgres@postgres.dev.svc.cluster.local:5432/postgres"
  REDIS_URL: "redis://redis.dev.svc.cluster.local:6379"
  PORT: "4000" 