apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
data:
  health_check.sh: |
    {{ .Files.Get "scripts/health_check.sh" | nindent 8 }}
  log_analysis.sh: |
    {{ .Files.Get "scripts/log_analysis.sh" | nindent 8 }}