apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  ports:
  - name: frontend
    port: 3000
    targetPort: 3000
  - name: backend
    port: 4000
    targetPort: 4000
  - name: db
    port: 5432
    targetPort: 5432
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: {{ .Release.Name }}-app